# Copyright 2015, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use
# this file except in compliance with the License. You may obtain a copy of the
# License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable
# law or agreed to in writing, software distributed under the License is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and
# limitations under the License.

machine:
  environment:
    # Add app engine sdk to pythonpath for local unit tests.
    # PYTHONPATH: ${PYTHONPATH}:${HOME}/google_appengine
    # Replace this with your project ID
    GCLOUD_PROJECT: "msds-434-project-275301"

dependencies:
  pre:
    # Download App Engine SDK
    # This is not necessary to deploy, its only necessary  to run local tests importing the App Engine SDK
    # - curl -o $HOME/google_appengine_1.9.30.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.30.zip
    # - unzip -q -d $HOME $HOME/google_appengine_1.9.30.zip
    # Retrieve our secrets from the CircleCI environment
    #- echo $CLIENT_SECRET | base64 --decode > ${HOME}/client-secret.json
    #- sed  s/YOUR-API-KEY/$API_KEY/ api_key.py.sample > api_key.py
    # vendor our dependencies
    - mkdir -p lib
    - pip install -r requirements.txt -t lib
    # Make sure gcloud is up to date
    - gcloud --quiet components update app
    # authenticate gcloud
    #- gcloud auth activate-service-account --key-file ${HOME}/client-secret.json
    # Replace <your-project-id>
    - gcloud config set project msds-434-project-275301

test:
  override:
    # run local unit tests
    # - python test_main.py

deployment:
    staging:
        branch: master
        commands:
        # deploy to AppEngine
        - gcloud -q app deploy final_project/* --promote --version=1
        # Run our E2E Test
        # - python e2e_test.py